### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by sophiajt** [skim-rs/skim#293]
Is there interesting in adding Windows support, by chance?  With more recent libraries, like crossterm, and the new tui libraries, there's more available to build on than when https://github.com/lotabout/skim/issues/25 was originally asked.

**Comment by lotabout** [comment]
@jonathandturner I am actually trying to use crossterm for window's support. But for now there are some blocking issues.

Currently:
- [ ] https://github.com/crossterm-rs/crossterm/issues/396
- [ ] https://github.com/crossterm-rs/crossterm/issues/397

**Comment by prabirshrestha** [comment]
What about [termwiz](https://docs.rs/termwiz/) which is also portable across multiple OS including Windows. It is used in [wezterm](https://wezfurlong.org/wezterm/) which is another gpu accelerated terminal written in rust.

It has [BufferedTerminal](https://github.com/wez/wezterm/blob/ea401e1f58ca5a088ac5d5e1d7963f36269afb76/termwiz/examples/buffered_terminal.rs) for optimal writes to terminal so it only writes deltas as well as first class support for [Widgets](https://github.com/wez/wezterm/blob/ea401e1f58ca5a088ac5d5e1d7963f36269afb76/termwiz/examples/widgets_basic.rs).

**Comment by lotabout** [comment]
@prabirshrestha Thanks for point out `termwiz`, I'll have a look.

**Comment by SirWindfield** [comment]
I was super excited to have a library that offers advanced fuzzy search. Not a binary, a library that I can embed as well in my applications.
Windows support would be really nice to have! Anything I can do to help? 🤔

**Comment by jonathandturner** [comment]
@lotabout - are there any updates on skim supporting Windows?

**Comment by rnag** [comment]
I would definitely to some length be interested in Windows support, in case that were ever to be a thing. I'm using a Windows 11 64-bit PC and currently rocking a Powershell console (which doesn't support emojis either, which is a bummer), so I think it would be cool to see `sk` supporting Windows if possible. Tbh I'm planning to use this in another project I'm still exploring, so likely in my case just envisioning this as a dependency rather than a binary such as `sk`; though a binary for windows would also be a neat idea, of course.

**Comment by StaticPH** [comment]
If possible, I'd like to see this done in a way that doesn't rely on `ConPTY`, which would both make it unusable on Windows 7-8.1 (and Windows 10 systems somehow still without 1809), and can be a significant performance bottleneck due to the Win32 API translation required for applications outputting escape sequences directly, which is necessary to remain compatible with existing Win32 applications. Furthermore, relying on `ConPTY` may impact the supported escape sequences independently from the console emulator support; this is at least one reason why few Windows terminals properly support the mouse. I don't believe mouse support is of particular concern for `skim`, but perhaps some other escape sequences may prove problematic.
My experience as an end user is that programs using `crossterm`, compared to those using `pancurses` (and by extension, `cursive`), are often unusable without `winpty`, hobbled even with `winpty`, and in some cases, can even manage to be less usable in something like `mintty` (with or without `winpty`) than in plain `cmd.exe`
One example of `crossterm` vs `pancurses` is [git-interactive-rebase-tool](https://github.com/MitMaro/git-interactive-rebase-tool), which switched from using `pancurses` to `crossterm` between versions 1.2.1 and 2.0.0. From 2.0.0 onward, on my old Windows 7 laptop, it has output raw escape sequences when using `winpty`, and ignores the terminal window size and user inputs in `mintty` without `winpty`. Version 1.2.1 continues to work fine on that machine, using `winpty`. I can't actually say definitively that this is `crossterm`'s fault, but I've had far more trouble using programs built with `crossterm` than with `pancurses`.

**Comment by agroszer** [comment]
@lotabout any chance?

**Comment by poa00** [comment]
**FYI**: @rnag,

(Off-topic, I know, and 2 years late but at any rate...) 

The author of the PowerShell module, [Terminal-Icons](https://github.com/devblackops/Terminal-Icons), hasn't pulled this commit yet, but I believe that is their intention... FWIW I use this in module PowerShell, and IMO it's awesome. 

In the meantime, [**here**](https://github.com/devblackops/Terminal-Icons/compare/main...aelij:TerminalIcons:feature/emoji) is the link to a branch with **added emoji support**. Hope that helps!

**Comment by LoicRiegel** [comment]
Hi, may I ask what's the status of this issue?
Do you have a rough idea of when support for Windows could be added?

**Comment by LoricAndre** [comment]
A rewrite of the TUI using ratatui is in progress, which should be a big first step. Windows support will be a priority after that.

**Comment by kvnxiao** [comment]
Apologies for the bump, but is there any updates to this or is it already on the roadmap for future releases?

**Comment by LoricAndre** [comment]
Someone started a PR but it looks abandoned, I'll pick it up when I have the time and motivation to setup a windows dev environment

**Comment by luoye00** [comment]
> Someone started a PR but it looks abandoned, I'll pick it up when I have the time and motivation to setup a windows dev environment

Great!

**Comment by LoricAndre** [comment]
I have a PR that looks quite good to me. Would anyone care to test it out on windows and give me feedback ? I should be able to provide binaries if needed, but I've had bad experiences with windows packaging in the past

**Comment by brian6932** [comment]
I built the PR, and it seems to work. It seems to hijack my scroll wheel and consume some of stdout even after I exit it though.

1. `sk`
1. Press <kbd>CTRL</kbd>+<kbd>C</kbd> or <kbd>ESC</kbd>
1. Scroll
1. Now it's using my scroll wheel in my prompt instead of scrolling the terminal.


Env info:
```pwsh
~
❯ alacritty -V
alacritty 0.17.0-dev (39d94d1f)
~
❯ pwsh -V
PowerShell 7.6.0-rc.1
~
❯ $_=Get-ItemProperty 'HKLM:/SOFTWARE/Microsoft/Windows NT/CurrentVersion';$_.CurrentMajorVersionNumber.ToString()+'.'+$_.CurrentMinorVersionNumber.ToString()+'.'+$_.CurrentBuild+'.'+$_.UBR
10.0.19044.6937
```

**Comment by LoricAndre** [comment]
@brian6932 thank you so much, could you please try again when you can ? I pushed a fix

**Comment by brian6932** [comment]
Still have the same problem on 3658295e when pressing <kbd>CTRL</kbd>+<kbd>C</kbd>, <kbd>ESC</kbd> seems to be fixed though.

**Comment by LoricAndre** [comment]
It seems windows intercepts `ctrl-c` and simply kills the current process. I'll fix this as cleanly as I can

**Comment by brian6932** [comment]
There's a signal that's sent on <kbd>CTRL</kbd>+<kbd>C</kbd> https://learn.microsoft.com/windows/console/ctrl-c-and-ctrl-break-signals https://learn.microsoft.com/windows/console/setconsolectrlhandler.

**Comment by LoricAndre** [comment]
Thank you for the tip, the handler should be installed on entering the TUI now, could you please check again ?

**Comment by brian6932** [comment]
edb3dc23 works as expected 🎉.
